// Code generated by "stringer -type Token ."; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[EOF-1]
	_ = x[NUMBER-2]
	_ = x[STRING-3]
	_ = x[VARIABLE-4]
	_ = x[LET-5]
	_ = x[PRINT-6]
	_ = x[IF-7]
	_ = x[THEN-8]
	_ = x[ELSE-9]
	_ = x[FOR-10]
	_ = x[TO-11]
	_ = x[NEXT-12]
	_ = x[GOTO-13]
	_ = x[GOSUB-14]
	_ = x[RETURN-15]
	_ = x[CALL-16]
	_ = x[REM-17]
	_ = x[PEEK-18]
	_ = x[POKE-19]
	_ = x[END-20]
	_ = x[COMMA-21]
	_ = x[SEMICOLON-22]
	_ = x[PLUS-23]
	_ = x[MINUS-24]
	_ = x[AND-25]
	_ = x[OR-26]
	_ = x[XOR-27]
	_ = x[ASTR-28]
	_ = x[SLASH-29]
	_ = x[MOD-30]
	_ = x[HASH-31]
	_ = x[LPAREN-32]
	_ = x[RPAREN-33]
	_ = x[LT-34]
	_ = x[GT-35]
	_ = x[LEQ-36]
	_ = x[GEQ-37]
	_ = x[NEQ-38]
	_ = x[EQ-39]
	_ = x[CR-40]
}

const _Token_name = "ERROREOFNUMBERSTRINGVARIABLELETPRINTIFTHENELSEFORTONEXTGOTOGOSUBRETURNCALLREMPEEKPOKEENDCOMMASEMICOLONPLUSMINUSANDORXORASTRSLASHMODHASHLPARENRPARENLTGTLEQGEQNEQEQCR"

var _Token_index = [...]uint8{0, 5, 8, 14, 20, 28, 31, 36, 38, 42, 46, 49, 51, 55, 59, 64, 70, 74, 77, 81, 85, 88, 93, 102, 106, 111, 114, 116, 119, 123, 128, 131, 135, 141, 147, 149, 151, 154, 157, 160, 162, 164}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
