// Code generated by "stringer -type Token"; DO NOT EDIT

package lex

import "fmt"

const _Token_name = "ERROREOFNUMBERSTRINGVARIABLELETPRINTIFTHENELSEFORTONEXTGOTOGOSUBRETURNCALLREMPEEKPOKEENDCOMMASEMICOLONPLUSMINUSANDORXORASTRSLASHMODHASHLPARENRPARENLTGTLEQGEQNEQEQCR"

var _Token_index = [...]uint8{0, 5, 8, 14, 20, 28, 31, 36, 38, 42, 46, 49, 51, 55, 59, 64, 70, 74, 77, 81, 85, 88, 93, 102, 106, 111, 114, 116, 119, 123, 128, 131, 135, 141, 147, 149, 151, 154, 157, 160, 162, 164}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
